name: Build

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        submodules: recursive
    - name: MSBuild
      run: |
        nuget restore D2RModMaker.sln
        msbuild /t:D2RModMaker:Rebuild /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None D2RModMaker.sln
    - name: Zip release
      uses: thedoctor0/zip-release@0.6.0
      with:
        directory: D2RModMaker\bin\Release\net5.0-windows
        filename: D2RModMaker.zip
        exclusions: |
          ref/*
    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: D2RModMaker.zip